project_id = "yyimbqztblquyqerbpls"

[functions.send-email]
verify_jwt = false

[functions.notify-admin]
verify_jwt = false

[functions.generate-quest-image]
verify_jwt = false

[functions.notify-users]
verify_jwt = false

[functions.recommend-squads]
verify_jwt = false
